apiVersion: v1
kind: Secret
metadata:
  name: family-order-secret
  namespace: family-order
type: Opaque
stringData:
  DATABASE_DSN: "pgsql:family_order:family_order@tcp(postgres:5432)/family_order?sslmode=disable"
  DATABASE_PASSWORD: "family_order"
  JWT_SECRET: "please-change-me"
  WECHAT_APP_SECRET: "please-change-me"
